# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5aa9bdbec20ad92ce5cf0e8ac2e044407ebc82630265b8d12ce273629655ff95f0e72a6d603cbddb5c5f7ff5d334794b59c47a8317ed4cafb626de39e039e16

test:
  secret_key_base: 96fe41971a59e0b68f8ed785ebf03eaf818e57a1fd23b57e307f1f4278d15cecef985c98ea957265d7f288196971183f3910258f7d230011ce25f51639a63083

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
